//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibrarySystem.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btncancelar {
            get {
                return ResourceManager.GetString("btncancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string btnclear {
            get {
                return ResourceManager.GetString("btnclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string btnclose {
            get {
                return ResourceManager.GetString("btnclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btndelete {
            get {
                return ResourceManager.GetString("btndelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar lista de libros.
        /// </summary>
        internal static string btnlistbooks {
            get {
                return ResourceManager.GetString("btnlistbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string btnlogout {
            get {
                return ResourceManager.GetString("btnlogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string btnnew {
            get {
                return ResourceManager.GetString("btnnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string btnok {
            get {
                return ResourceManager.GetString("btnok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrasado.
        /// </summary>
        internal static string btnoverdue {
            get {
                return ResourceManager.GetString("btnoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avance.
        /// </summary>
        internal static string btnpreview {
            get {
                return ResourceManager.GetString("btnpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string btnreturn {
            get {
                return ResourceManager.GetString("btnreturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedir prestado.
        /// </summary>
        internal static string btnrorrow {
            get {
                return ResourceManager.GetString("btnrorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N. total de libros.
        /// </summary>
        internal static string btntotalnobooks {
            get {
                return ResourceManager.GetString("btntotalnobooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string btnupdate {
            get {
                return ResourceManager.GetString("btnupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de acceso.
        /// </summary>
        internal static string colaccessionno {
            get {
                return ResourceManager.GetString("colaccessionno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del libro.
        /// </summary>
        internal static string colbookdesc {
            get {
                return ResourceManager.GetString("colbookdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor.
        /// </summary>
        internal static string colbookpuplisher {
            get {
                return ResourceManager.GetString("colbookpuplisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo del libro.
        /// </summary>
        internal static string colbooktitle {
            get {
                return ResourceManager.GetString("colbooktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prestatario.
        /// </summary>
        internal static string colborrower {
            get {
                return ResourceManager.GetString("colborrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string colcategoryid {
            get {
                return ResourceManager.GetString("colcategoryid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Prestamo.
        /// </summary>
        internal static string coldateborrowed {
            get {
                return ResourceManager.GetString("coldateborrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de devolucion.
        /// </summary>
        internal static string coldatereturned {
            get {
                return ResourceManager.GetString("coldatereturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string coldescription {
            get {
                return ResourceManager.GetString("coldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Vencimiento.
        /// </summary>
        internal static string colduedate {
            get {
                return ResourceManager.GetString("colduedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N. de Copias.
        /// </summary>
        internal static string colnocopies {
            get {
                return ResourceManager.GetString("colnocopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string colprice {
            get {
                return ResourceManager.GetString("colprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proposito.
        /// </summary>
        internal static string colpurpose {
            get {
                return ResourceManager.GetString("colpurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observacion.
        /// </summary>
        internal static string colremark {
            get {
                return ResourceManager.GetString("colremark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string colstate {
            get {
                return ResourceManager.GetString("colstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string frm_login {
            get {
                return ResourceManager.GetString("frm_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string frmbooks {
            get {
                return ResourceManager.GetString("frmbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamo de libros.
        /// </summary>
        internal static string frmborowbooks {
            get {
                return ResourceManager.GetString("frmborowbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prestatario.
        /// </summary>
        internal static string frmborrowers {
            get {
                return ResourceManager.GetString("frmborrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías de libros.
        /// </summary>
        internal static string frmcategories {
            get {
                return ResourceManager.GetString("frmcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros de usuario.
        /// </summary>
        internal static string frmlogs {
            get {
                return ResourceManager.GetString("frmlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago.
        /// </summary>
        internal static string frmoverdue {
            get {
                return ResourceManager.GetString("frmoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de biblioteca.
        /// </summary>
        internal static string frmprincipal {
            get {
                return ResourceManager.GetString("frmprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes de inventario.
        /// </summary>
        internal static string frmreport {
            get {
                return ResourceManager.GetString("frmreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devuelto.
        /// </summary>
        internal static string frmreturned {
            get {
                return ResourceManager.GetString("frmreturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar usuarios.
        /// </summary>
        internal static string frmuser {
            get {
                return ResourceManager.GetString("frmuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string groupbooks {
            get {
                return ResourceManager.GetString("groupbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del libro.
        /// </summary>
        internal static string groupbooksdetails {
            get {
                return ResourceManager.GetString("groupbooksdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro de fecha.
        /// </summary>
        internal static string groupdatefilter {
            get {
                return ResourceManager.GetString("groupdatefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles de libros no devueltos.
        /// </summary>
        internal static string groupdetails {
            get {
                return ResourceManager.GetString("groupdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de libros prestados.
        /// </summary>
        internal static string grouplistofborrowedbooks {
            get {
                return ResourceManager.GetString("grouplistofborrowedbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago por horas.
        /// </summary>
        internal static string grouppaymenthours {
            get {
                return ResourceManager.GetString("grouppaymenthours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        internal static string grouppayments {
            get {
                return ResourceManager.GetString("grouppayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prestado.
        /// </summary>
        internal static string itemborrowed {
            get {
                return ResourceManager.GetString("itemborrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficción.
        /// </summary>
        internal static string itemfiction {
            get {
                return ResourceManager.GetString("itemfiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ficción.
        /// </summary>
        internal static string itemnonfiction {
            get {
                return ResourceManager.GetString("itemnonfiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrasado.
        /// </summary>
        internal static string itemoverdue {
            get {
                return ResourceManager.GetString("itemoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Durante la noche.
        /// </summary>
        internal static string itemovernight {
            get {
                return ResourceManager.GetString("itemovernight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotocopia.
        /// </summary>
        internal static string itemphotocopy {
            get {
                return ResourceManager.GetString("itemphotocopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Investigar.
        /// </summary>
        internal static string itemresearch {
            get {
                return ResourceManager.GetString("itemresearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devuelto.
        /// </summary>
        internal static string itemreturned {
            get {
                return ResourceManager.GetString("itemreturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        internal static string itemunknown {
            get {
                return ResourceManager.GetString("itemunknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N. de acceso:.
        /// </summary>
        internal static string lbaccession {
            get {
                return ResourceManager.GetString("lbaccession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lbadress {
            get {
                return ResourceManager.GetString("lbadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto:.
        /// </summary>
        internal static string lbamount {
            get {
                return ResourceManager.GetString("lbamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor:.
        /// </summary>
        internal static string lbauthor {
            get {
                return ResourceManager.GetString("lbauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo del libro:.
        /// </summary>
        internal static string lbbooktitle {
            get {
                return ResourceManager.GetString("lbbooktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id del prestatario:.
        /// </summary>
        internal static string lbborrowerid {
            get {
                return ResourceManager.GetString("lbborrowerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del prestatario:.
        /// </summary>
        internal static string lbborrowername {
            get {
                return ResourceManager.GetString("lbborrowername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria:.
        /// </summary>
        internal static string lbcategory {
            get {
                return ResourceManager.GetString("lbcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio:.
        /// </summary>
        internal static string lbchange {
            get {
                return ResourceManager.GetString("lbchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N. de contacto:.
        /// </summary>
        internal static string lbcontactno {
            get {
                return ResourceManager.GetString("lbcontactno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lbcontrasena {
            get {
                return ResourceManager.GetString("lbcontrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso / Año:.
        /// </summary>
        internal static string lbcourse {
            get {
                return ResourceManager.GetString("lbcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha publicación:.
        /// </summary>
        internal static string lbdate {
            get {
                return ResourceManager.GetString("lbdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string lbdescripcion {
            get {
                return ResourceManager.GetString("lbdescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string lbdescription {
            get {
                return ResourceManager.GetString("lbdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final.
        /// </summary>
        internal static string lbdeweydecimal {
            get {
                return ResourceManager.GetString("lbdeweydecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final.
        /// </summary>
        internal static string lbenddate {
            get {
                return ResourceManager.GetString("lbenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer nombre:.
        /// </summary>
        internal static string lbfirstname {
            get {
                return ResourceManager.GetString("lbfirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hora.
        /// </summary>
        internal static string lbhour {
            get {
                return ResourceManager.GetString("lbhour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hora(as).
        /// </summary>
        internal static string lbhr {
            get {
                return ResourceManager.GetString("lbhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido:.
        /// </summary>
        internal static string lblastname {
            get {
                return ResourceManager.GetString("lblastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo nombre:.
        /// </summary>
        internal static string lbmiddlename {
            get {
                return ResourceManager.GetString("lbmiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lbname {
            get {
                return ResourceManager.GetString("lbname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo vencido:.
        /// </summary>
        internal static string lboverduetme {
            get {
                return ResourceManager.GetString("lboverduetme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lbpassword {
            get {
                return ResourceManager.GetString("lbpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles de libros no devueltos con penalizaciones.
        /// </summary>
        internal static string lbpaymentgroup {
            get {
                return ResourceManager.GetString("lbpaymentgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a por.
        /// </summary>
        internal static string lbper {
            get {
                return ResourceManager.GetString("lbper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor:.
        /// </summary>
        internal static string lbpublisher {
            get {
                return ResourceManager.GetString("lbpublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propósito.
        /// </summary>
        internal static string lbpurpose {
            get {
                return ResourceManager.GetString("lbpurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regreso.
        /// </summary>
        internal static string lbreturn {
            get {
                return ResourceManager.GetString("lbreturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda:.
        /// </summary>
        internal static string lbsearch {
            get {
                return ResourceManager.GetString("lbsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo:.
        /// </summary>
        internal static string lbsexo {
            get {
                return ResourceManager.GetString("lbsexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio.
        /// </summary>
        internal static string lbstartdate {
            get {
                return ResourceManager.GetString("lbstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        internal static string lbstatus {
            get {
                return ResourceManager.GetString("lbstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto ofrecido:.
        /// </summary>
        internal static string lbtendererd {
            get {
                return ResourceManager.GetString("lbtendererd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string lbtitle {
            get {
                return ResourceManager.GetString("lbtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos totales:.
        /// </summary>
        internal static string lbtotalpayments {
            get {
                return ResourceManager.GetString("lbtotalpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        internal static string lbtype {
            get {
                return ResourceManager.GetString("lbtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de libros:.
        /// </summary>
        internal static string lbtypebooks {
            get {
                return ResourceManager.GetString("lbtypebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lbusername {
            get {
                return ResourceManager.GetString("lbusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string lbusuario {
            get {
                return ResourceManager.GetString("lbusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles de libros no devueltos.
        /// </summary>
        internal static string lbviewdetailsofunreturnbooks {
            get {
                return ResourceManager.GetString("lbviewdetailsofunreturnbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año / Sección:.
        /// </summary>
        internal static string lbyessection {
            get {
                return ResourceManager.GetString("lbyessection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás seguro de que quieres cambiar el idioma a Español..
        /// </summary>
        internal static string msgcamidiomaespanol {
            get {
                return ResourceManager.GetString("msgcamidiomaespanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás seguro de que quieres cambiar el idioma a inglés..
        /// </summary>
        internal static string msgcamidiomaingles {
            get {
                return ResourceManager.GetString("msgcamidiomaingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion.
        /// </summary>
        internal static string msgconfirmacion {
            get {
                return ResourceManager.GetString("msgconfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte diario.
        /// </summary>
        internal static string rddailyreport {
            get {
                return ResourceManager.GetString("rddailyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mujer.
        /// </summary>
        internal static string rdfemale {
            get {
                return ResourceManager.GetString("rdfemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        internal static string rdmale {
            get {
                return ResourceManager.GetString("rdmale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte mensual.
        /// </summary>
        internal static string rdmonthlyreport {
            get {
                return ResourceManager.GetString("rdmonthlyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte semanal.
        /// </summary>
        internal static string rdweeklyreport {
            get {
                return ResourceManager.GetString("rdweeklyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar libros.
        /// </summary>
        internal static string subbook {
            get {
                return ResourceManager.GetString("subbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar prestatarios.
        /// </summary>
        internal static string subborowers {
            get {
                return ResourceManager.GetString("subborowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros Prestados.
        /// </summary>
        internal static string subborrowedbooks {
            get {
                return ResourceManager.GetString("subborrowedbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string subdetail {
            get {
                return ResourceManager.GetString("subdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string subenglis {
            get {
                return ResourceManager.GetString("subenglis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string subfile {
            get {
                return ResourceManager.GetString("subfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar categorías.
        /// </summary>
        internal static string subfilecategori {
            get {
                return ResourceManager.GetString("subfilecategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string sublenguaje {
            get {
                return ResourceManager.GetString("sublenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        internal static string sublogout {
            get {
                return ResourceManager.GetString("sublogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string subreports {
            get {
                return ResourceManager.GetString("subreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros devueltos.
        /// </summary>
        internal static string subreturnedbooks {
            get {
                return ResourceManager.GetString("subreturnedbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string subspanish {
            get {
                return ResourceManager.GetString("subspanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros no devueltos.
        /// </summary>
        internal static string subunreturnbooks {
            get {
                return ResourceManager.GetString("subunreturnbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros de usuario.
        /// </summary>
        internal static string subuserlogs {
            get {
                return ResourceManager.GetString("subuserlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar usuarios.
        /// </summary>
        internal static string subusers {
            get {
                return ResourceManager.GetString("subusers", resourceCulture);
            }
        }
    }
}
