//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibrarySystem.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btncancelar {
            get {
                return ResourceManager.GetString("btncancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnclear {
            get {
                return ResourceManager.GetString("btnclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnclose {
            get {
                return ResourceManager.GetString("btnclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btndelete {
            get {
                return ResourceManager.GetString("btndelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Books.
        /// </summary>
        internal static string btnlistbooks {
            get {
                return ResourceManager.GetString("btnlistbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string btnlogout {
            get {
                return ResourceManager.GetString("btnlogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnnew {
            get {
                return ResourceManager.GetString("btnnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnok {
            get {
                return ResourceManager.GetString("btnok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Due.
        /// </summary>
        internal static string btnoverdue {
            get {
                return ResourceManager.GetString("btnoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btnpreview {
            get {
                return ResourceManager.GetString("btnpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string btnreturn {
            get {
                return ResourceManager.GetString("btnreturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string btnrorrow {
            get {
                return ResourceManager.GetString("btnrorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No. of Books.
        /// </summary>
        internal static string btntotalnobooks {
            get {
                return ResourceManager.GetString("btntotalnobooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnupdate {
            get {
                return ResourceManager.GetString("btnupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesion.
        /// </summary>
        internal static string frm_login {
            get {
                return ResourceManager.GetString("frm_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string frmbooks {
            get {
                return ResourceManager.GetString("frmbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borow Books.
        /// </summary>
        internal static string frmborowbooks {
            get {
                return ResourceManager.GetString("frmborowbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower.
        /// </summary>
        internal static string frmborrowers {
            get {
                return ResourceManager.GetString("frmborrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Categories.
        /// </summary>
        internal static string frmcategories {
            get {
                return ResourceManager.GetString("frmcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logs.
        /// </summary>
        internal static string frmlogs {
            get {
                return ResourceManager.GetString("frmlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string frmoverdue {
            get {
                return ResourceManager.GetString("frmoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library System.
        /// </summary>
        internal static string frmprincipal {
            get {
                return ResourceManager.GetString("frmprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Reports.
        /// </summary>
        internal static string frmreport {
            get {
                return ResourceManager.GetString("frmreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        internal static string frmreturned {
            get {
                return ResourceManager.GetString("frmreturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string frmuser {
            get {
                return ResourceManager.GetString("frmuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string groupbooks {
            get {
                return ResourceManager.GetString("groupbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book`s Details.
        /// </summary>
        internal static string groupbooksdetails {
            get {
                return ResourceManager.GetString("groupbooksdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Filter.
        /// </summary>
        internal static string groupdatefilter {
            get {
                return ResourceManager.GetString("groupdatefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details of Unreturn Books.
        /// </summary>
        internal static string groupdetails {
            get {
                return ResourceManager.GetString("groupdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Per Hours.
        /// </summary>
        internal static string grouppaymenthours {
            get {
                return ResourceManager.GetString("grouppaymenthours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string grouppayments {
            get {
                return ResourceManager.GetString("grouppayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed.
        /// </summary>
        internal static string itemborrowed {
            get {
                return ResourceManager.GetString("itemborrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction.
        /// </summary>
        internal static string itemfiction {
            get {
                return ResourceManager.GetString("itemfiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Fiction.
        /// </summary>
        internal static string itemnonfiction {
            get {
                return ResourceManager.GetString("itemnonfiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string itemoverdue {
            get {
                return ResourceManager.GetString("itemoverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        internal static string itemreturned {
            get {
                return ResourceManager.GetString("itemreturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string itemunknown {
            get {
                return ResourceManager.GetString("itemunknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accession No:.
        /// </summary>
        internal static string lbaccession {
            get {
                return ResourceManager.GetString("lbaccession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress:.
        /// </summary>
        internal static string lbadress {
            get {
                return ResourceManager.GetString("lbadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string lbamount {
            get {
                return ResourceManager.GetString("lbamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string lbauthor {
            get {
                return ResourceManager.GetString("lbauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Title:.
        /// </summary>
        internal static string lbbooktitle {
            get {
                return ResourceManager.GetString("lbbooktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower Id:.
        /// </summary>
        internal static string lbborrowerid {
            get {
                return ResourceManager.GetString("lbborrowerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower Name:.
        /// </summary>
        internal static string lbborrowername {
            get {
                return ResourceManager.GetString("lbborrowername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string lbcategory {
            get {
                return ResourceManager.GetString("lbcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        internal static string lbchange {
            get {
                return ResourceManager.GetString("lbchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.:.
        /// </summary>
        internal static string lbcontactno {
            get {
                return ResourceManager.GetString("lbcontactno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        internal static string lbcontrasena {
            get {
                return ResourceManager.GetString("lbcontrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course/Year:.
        /// </summary>
        internal static string lbcourse {
            get {
                return ResourceManager.GetString("lbcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Publish:.
        /// </summary>
        internal static string lbdate {
            get {
                return ResourceManager.GetString("lbdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string lbdescripcion {
            get {
                return ResourceManager.GetString("lbdescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string lbdescription {
            get {
                return ResourceManager.GetString("lbdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dewey Decimal:.
        /// </summary>
        internal static string lbdeweydecimal {
            get {
                return ResourceManager.GetString("lbdeweydecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string lbenddate {
            get {
                return ResourceManager.GetString("lbenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string lbfirstname {
            get {
                return ResourceManager.GetString("lbfirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string lbhour {
            get {
                return ResourceManager.GetString("lbhour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr(s).
        /// </summary>
        internal static string lbhr {
            get {
                return ResourceManager.GetString("lbhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string lblastname {
            get {
                return ResourceManager.GetString("lblastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        internal static string lbmiddlename {
            get {
                return ResourceManager.GetString("lbmiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lbname {
            get {
                return ResourceManager.GetString("lbname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Time:.
        /// </summary>
        internal static string lboverduetme {
            get {
                return ResourceManager.GetString("lboverduetme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lbpassword {
            get {
                return ResourceManager.GetString("lbpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details of unreturned books with Penalties.
        /// </summary>
        internal static string lbpaymentgroup {
            get {
                return ResourceManager.GetString("lbpaymentgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        internal static string lbper {
            get {
                return ResourceManager.GetString("lbper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        internal static string lbpublisher {
            get {
                return ResourceManager.GetString("lbpublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string lbsearch {
            get {
                return ResourceManager.GetString("lbsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex:.
        /// </summary>
        internal static string lbsexo {
            get {
                return ResourceManager.GetString("lbsexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lbstartdate {
            get {
                return ResourceManager.GetString("lbstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string lbstatus {
            get {
                return ResourceManager.GetString("lbstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tendered Amount:.
        /// </summary>
        internal static string lbtendererd {
            get {
                return ResourceManager.GetString("lbtendererd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string lbtitle {
            get {
                return ResourceManager.GetString("lbtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payments:.
        /// </summary>
        internal static string lbtotalpayments {
            get {
                return ResourceManager.GetString("lbtotalpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string lbtype {
            get {
                return ResourceManager.GetString("lbtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Books:.
        /// </summary>
        internal static string lbtypebooks {
            get {
                return ResourceManager.GetString("lbtypebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        internal static string lbusername {
            get {
                return ResourceManager.GetString("lbusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lbusuario {
            get {
                return ResourceManager.GetString("lbusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Report.
        /// </summary>
        internal static string rddailyreport {
            get {
                return ResourceManager.GetString("rddailyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string rdfemale {
            get {
                return ResourceManager.GetString("rdfemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string rdmale {
            get {
                return ResourceManager.GetString("rdmale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Report.
        /// </summary>
        internal static string rdmonthlyreport {
            get {
                return ResourceManager.GetString("rdmonthlyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Report.
        /// </summary>
        internal static string rdweeklyreport {
            get {
                return ResourceManager.GetString("rdweeklyreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Books.
        /// </summary>
        internal static string subbook {
            get {
                return ResourceManager.GetString("subbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Borowers.
        /// </summary>
        internal static string subborowers {
            get {
                return ResourceManager.GetString("subborowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string subfile {
            get {
                return ResourceManager.GetString("subfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Categories.
        /// </summary>
        internal static string subfilecategori {
            get {
                return ResourceManager.GetString("subfilecategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string subreports {
            get {
                return ResourceManager.GetString("subreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Books.
        /// </summary>
        internal static string subreturnedbooks {
            get {
                return ResourceManager.GetString("subreturnedbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreturn Books.
        /// </summary>
        internal static string subunreturnbooks {
            get {
                return ResourceManager.GetString("subunreturnbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logs.
        /// </summary>
        internal static string subuserlogs {
            get {
                return ResourceManager.GetString("subuserlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string subusers {
            get {
                return ResourceManager.GetString("subusers", resourceCulture);
            }
        }
    }
}
